Models/Actor.cs
namespace Employee.Models
{
    public class Actor
    {
        public int Id { get; set; }
        public string FirstName{ get; set; }
        public string LastName { get; set; }
        public string  Bio { get; set; }

        public ICollection<Actor_Movie> Actors_Movies { get; set; }

       
    }
}

Models/Actor_Movie.cs
namespace Employee.Models
{
    public class Actor_Movie
    {
        public int Id { get; set; }
        public int ActorId { get; set; }
        public Actor Actor { get; set; }


        public int MovieId { get; set; }
        public Movie Movie { get; set; }

        public Actor_Movie Actors_Movies { get; set; }
    }
}

Models/Cinema.cs
namespace Employee.Models
{
    public class Cinema
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public ICollection<Movie> Movies { get; set; }
    }
}

Models/EmployementData.cs
using Employee.Data;
using System.ComponentModel.DataAnnotations;

namespace Employee.Models
{
    public class EmployementData
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        [Required]
        public string Department { get; set; }
        
        [Required]
        public int Salary { get; set; }
        [Required]
        public int Service { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace Employee.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Movie.cs
using Employee.Data;
using System.ComponentModel.DataAnnotations.Schema;

namespace Employee.Models
{
    public class Movie
    {
        public int Id { get; set; } 
        public DateTime StartDate { get; set; }
        public DateTime EndDate{ get; set; }
        public int Price { get; set; }
        public MovieCatagory MovieCatagory { get; set; }

        public ICollection<Actor_Movie> Actors_Movies { get; set; }

        public int CinemaId { get; set; }
        [ForeignKey("CinemaId")]
        public Cinema Cinema { get; set; }

        public int ProducerId { get; set; }

        [ForeignKey("ProducerId")]
        public Producer Producer { get; set; }
    }
}

Models/Producer.cs
namespace Employee.Models
{
    public class Producer 
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Bio { get; set; }

        public ICollection<Movie> Movies { get; set; }
    }
}

Controllers/EmpController.cs
using Employee.Models;
using Employee.Data;
using Microsoft.AspNetCore.Mvc;

namespace Employee.Controllers
{
    public class EmpController : Controller
    {
        private readonly EmployeeDbContext _db;

        public EmpController(EmployeeDbContext db)
        {
            _db = db;
        }
        
        public IActionResult Index(string SearchString)
        {
            ViewData["CurrentFilter"] = SearchString;
            var SearchData = from b in _db.EmpData select b;
            if (!String.IsNullOrEmpty(SearchString))
            {
                SearchData = SearchData.Where(m => m.FirstName.Contains(SearchString));
                return View(SearchData);

            }
            IEnumerable<EmployementData> EmpDbLists = _db.EmpData;

            //var EmpDbLists = _db.EmpData.ToList();

            return View(EmpDbLists);
        }




        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(EmployementData obj)
        {
            if(ModelState.IsValid)
            {
                _db.EmpData.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Created successfully";
                return RedirectToAction("Index");
            }
          

            return View();
        }

        public IActionResult Edit(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var EditFoundFromDb = _db.EmpData.Find(id);

            return View(EditFoundFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(EmployementData obj)
        {

            if (ModelState.IsValid)
            {
                _db.EmpData.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Employee data edited successfully";
                return RedirectToAction("Index");

            }
            {
                NotFound();
            }


            return View();
        }

        public IActionResult Delete(int id)
        {
            if (id == 0 )
            {
                return NotFound();
            }
            var DeleteFromDb = _db.EmpData.Find(id);

            if (DeleteFromDb == null)
            {
                return NotFound();
            }

            return View(DeleteFromDb);
        }

        public IActionResult DeletePost(EmployementData obj)
        {
            if(obj == null)
            {
                return NotFound();
            }

            _db.EmpData.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Deleted successfully";
            return RedirectToAction("Index");
            //return View(obj);
            
        }

        

    }
}

Controllers/HomeController.cs
using Employee.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Employee.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Emp/Create.cshtml
@model EmployementData

<form method="post" class="container">
    <div class="row">
     
        <div>
            <label asp-for="FirstName"></label>
            <input asp-for="FirstName" class="form-control" />
        </div>
        <div>
            <label asp-for="LastName"></label>
            <input asp-for="LastName" class="form-control"/>
        </div>
        <div>
            <label asp-for="Department"></label>
            <input asp-for="Department"  class="form-control"/>
        </div>
        <div>
            <label asp-for="Salary"></label>
            <input asp-for="Salary" class="form-control"/>
        </div>
        <div >
            <label asp-for="Service"></label>
            <input asp-for="Service" class="form-control" />
        </div>
        <div class="pt-4">
            <button type="submit" class="btn btn-primary">Create</button>
            <a asp-controller="Emp" asp-action="index" class="btn btn-secondary">Back to the Lists</a>
        </div>
    </div>

</form>

Views/Emp/Delete.cshtml
@model EmployementData

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="container" >
        <div class="row" >
            <div >
                <label asp-for="FirstName"></label>
                <input asp-for="FirstName" disabled class="form-control"/>
            </div>
            <div >
                <label asp-for="LastName"></label>
                <input asp-for="LastName" disabled class="form-control"/>
            </div>
            <div >
                <label asp-for="Department"></label>
                <input asp-for="Department" disabled class="form-control"/>
            </div>
            <div>
                <label asp-for="Salary"></label>
                <input asp-for="Salary" disabled class="form-control"/>
            </div>
            <div >
                <label asp-for="Service" ></label>
                <input asp-for="Service" disabled class="form-control"/>
            </div>

        </div>
        <button class="btn btn-info" >Delete</button>
        <a asp-controller="Emp" asp-action="Index" class="btn btn-dark">Back to List</a>

    </div>

</form>

Views/Emp/Edit.cshtml
@model EmployementData

<form method="post" asp-action="Edit">
    <div class="container" >
        <div class="row" >
            <div >
                <label asp-for="FirstName"></label>
                <input asp-for="FirstName" class="form-control"/>
            </div>
            <div >
                <label asp-for="LastName"></label>
                <input asp-for="LastName" class="form-control"/>
            </div>
            <div >
                <label asp-for="Department"></label>
                <input asp-for="Department" class="form-control"/>
            </div>
            <div>
                <label asp-for="Salary"></label>
                <input asp-for="Salary" class="form-control"/>
            </div>
            <div >
                <label asp-for="Service" ></label>
                <input asp-for="Service" class="form-control"/>
            </div>

        </div>
        <button class="btn btn-info" >Update</button>
        <a asp-controller="Emp" asp-action="Index" class="btn btn-dark">Back to List</a>

    </div>

</form>

Views/Emp/Index.cshtml
@model IEnumerable<EmployementData>
@{
    ViewData["Title"] = "Index";
}
<partial name="_NotificationPartial" />

@*success for individual control*@
@*@if(TempData["success"]!= null)
{
    <h3>@TempData["success"]</h3>
}*@

<div class="container" style="width:100%" >
    <div class="row" >
        <div class="col-8">
        <form method="get">
           
           <input type="text"  name="SearchString" value="@ViewData["CurrentFilter"]"/>
           <input type="submit" class="btn btn-primary" value="Search" />
        </form>  
        </div>
        <div class="col-4">
           <a asp-controller="Emp" asp-action="Create" type="submit" class="btn btn-primary "  > Create Family </a>
        </div>
        
    </div>

   
       

<table class="table table-bordered table-striped" style="width:60%" >
    
    <thead>
        <tr>
            <th> Id </th>
            <th> FirstName </th>
            <th> LastName </th>
            <th> Department </th>
            <th> Salary </th>
            <th> Service </th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td width="50%" > @item.Id </td>
                <td width="50%" > @item.FirstName </td>
                <td width="50%"> @item.LastName </td>
                <td width="50%"> @item.Department </td>
                <td width="50%"> @item.Salary </td>
                <td width="50%"> @item.Service </td> 
                <td width="30%">
                    <div>
                        <a class="btn btn-primary" asp-controller="Emp" asp-action="Edit" asp-route-id="@item.Id" > Edit</a> 
                    </div>
                </td> 
                <td width="30%">
                    <div >
                        <a class="btn btn-info" asp-controller="Emp" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </div>
                </td>
            </tr>
            
        }
    </tbody>
   
    
</table>
    

</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Employee</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Employee.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
 <nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link text-dark"  asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-dark" asp-controller="Emp" asp-action="Index">Employee</a>
        </li>
       
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Employee - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_NotificationPartial.cshtml
@if(TempData["success"]!=null)
{
    <h2>@TempData["success"]</h2>
}

@if(TempData["error"]!=null)
{
    <h2>@TempData["error"]</h2>
}

Views/View.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@